# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-31 11:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u6807\u9898')),
                ('name_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u6807\u9898\uff08\u82f1\u6587\uff09')),
                ('explain', models.TextField(verbose_name='\u63cf\u8ff0')),
                ('explain_en', models.TextField(blank=True, null=True, verbose_name='\u63cf\u8ff0\uff08\u82f1\u6587\uff09')),
                ('order', models.IntegerField(default=0, verbose_name='\u987a\u5e8f\uff08\u53ea\u4f1a\u663e\u793a\u987a\u5e8f\u503c\u6700\u9ad8\u7684\u4e00\u5957Banner\uff09')),
                ('banner_bg', models.ImageField(upload_to='about_banner/%Y/%m', verbose_name='\u80cc\u666f\u56fe\u7247\uff081920*875\uff09')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u5173\u4e8e\u6211\u4eecBanner\u7ba1\u7406',
                'verbose_name_plural': '\u5173\u4e8e\u6211\u4eecBanner\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='ContactBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u6807\u9898')),
                ('name_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u6807\u9898\uff08\u82f1\u6587\uff09')),
                ('explain', models.TextField(verbose_name='\u63cf\u8ff0')),
                ('explain_en', models.TextField(blank=True, null=True, verbose_name='\u63cf\u8ff0\uff08\u82f1\u6587\uff09')),
                ('order', models.IntegerField(default=0, verbose_name='\u987a\u5e8f\uff08\u53ea\u4f1a\u663e\u793a\u987a\u5e8f\u503c\u6700\u9ad8\u7684\u4e00\u5957Banner\uff09')),
                ('banner_bg', models.ImageField(upload_to='about_banner/%Y/%m', verbose_name='\u80cc\u666f\u56fe\u7247\uff081920*875\uff09')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u8054\u7cfb\u6211\u4eecBanner\u7ba1\u7406',
                'verbose_name_plural': '\u8054\u7cfb\u6211\u4eecBanner\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='IndexBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u540d\u79f0\uff08\u8bc6\u522b\u4f5c\u7528\uff09')),
                ('background_video', models.FileField(upload_to='index_banner/%Y/%m', verbose_name='\u80cc\u666f\u89c6\u9891\uff08MP4\u683c\u5f0f\uff09')),
                ('banner_info', models.ImageField(upload_to='index_banner/%Y/%m', verbose_name='\u6d6e\u51fa\u56fe\u7247\uff08\u5efa\u8bae1300*350\u5de6\u53f3\uff09')),
                ('banner_info_en', models.ImageField(blank=True, null=True, upload_to='index_banner/%Y/%m', verbose_name='\u6d6e\u51fa\u56fe\u7247\uff08\u82f1\u6587\u9875\u97621300*350\u5de6\u53f3\uff09')),
                ('order', models.IntegerField(default=0, verbose_name='\u987a\u5e8f\uff08\u53ea\u4f1a\u663e\u793a\u987a\u5e8f\u503c\u6700\u9ad8\u7684\u4e00\u5957Banner\uff09')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u9996\u9875Banner\u7ba1\u7406',
                'verbose_name_plural': '\u9996\u9875Banner\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='InvestMentBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u6807\u9898')),
                ('name_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u6807\u9898\uff08\u82f1\u6587\uff09')),
                ('explain', models.TextField(verbose_name='\u63cf\u8ff0')),
                ('explain_en', models.TextField(blank=True, null=True, verbose_name='\u63cf\u8ff0\uff08\u82f1\u6587\uff09')),
                ('order', models.IntegerField(default=0, verbose_name='\u987a\u5e8f\uff08\u53ea\u4f1a\u663e\u793a\u987a\u5e8f\u503c\u6700\u9ad8\u7684\u4e00\u5957Banner\uff09')),
                ('banner_bg', models.ImageField(upload_to='about_banner/%Y/%m', verbose_name='\u80cc\u666f\u56fe\u7247\uff081920*875\uff09')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u6295\u8d44\u56e2\u961fBanner\u7ba1\u7406',
                'verbose_name_plural': '\u6295\u8d44\u56e2\u961fBanner\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='InvestProBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u6807\u9898')),
                ('name_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u6807\u9898\uff08\u82f1\u6587\uff09')),
                ('explain', models.TextField(verbose_name='\u63cf\u8ff0')),
                ('explain_en', models.TextField(blank=True, null=True, verbose_name='\u63cf\u8ff0\uff08\u82f1\u6587\uff09')),
                ('order', models.IntegerField(default=0, verbose_name='\u987a\u5e8f\uff08\u53ea\u4f1a\u663e\u793a\u987a\u5e8f\u503c\u6700\u9ad8\u7684\u4e00\u5957Banner\uff09')),
                ('banner_bg', models.ImageField(upload_to='about_banner/%Y/%m', verbose_name='\u80cc\u666f\u56fe\u7247\uff081920*875\uff09')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u6295\u8d44\u9879\u76eeBanner\u7ba1\u7406',
                'verbose_name_plural': '\u6295\u8d44\u9879\u76eeBanner\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='NewsBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u6807\u9898')),
                ('name_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u6807\u9898\uff08\u82f1\u6587\uff09')),
                ('explain', models.TextField(verbose_name='\u63cf\u8ff0')),
                ('explain_en', models.TextField(blank=True, null=True, verbose_name='\u63cf\u8ff0\uff08\u82f1\u6587\uff09')),
                ('order', models.IntegerField(default=0, verbose_name='\u987a\u5e8f\uff08\u53ea\u4f1a\u663e\u793a\u987a\u5e8f\u503c\u6700\u9ad8\u7684\u4e00\u5957Banner\uff09')),
                ('banner_bg', models.ImageField(upload_to='about_banner/%Y/%m', verbose_name='\u80cc\u666f\u56fe\u7247\uff081920*875\uff09')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u65b0\u95fb\u62a5\u9053Banner\u7ba1\u7406',
                'verbose_name_plural': '\u65b0\u95fb\u62a5\u9053Banner\u7ba1\u7406',
            },
        ),
    ]
