# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-01 00:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='\u5c55\u793a\u6807\u9898')),
                ('title_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u5c55\u793a\u6807\u9898\uff08\u82f1\u6587\uff09')),
                ('explain', models.TextField(verbose_name='\u63cf\u8ff0\u6587\u5b57')),
                ('explain_en', models.TextField(blank=True, null=True, verbose_name='\u63cf\u8ff0\u6587\u5b57\uff08\u82f1\u6587\uff09')),
                ('order', models.IntegerField(default=0, verbose_name='\u987a\u5e8f\uff08\u53ea\u663e\u793a\u987a\u5e8f\u503c\u6700\u5927\u7684\u5185\u5bb9\uff09')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u5173\u4e8e\u6211\u4eec\u5185\u5bb9',
                'verbose_name_plural': '\u5173\u4e8e\u6211\u4eec\u5185\u5bb9',
            },
        ),
        migrations.CreateModel(
            name='HonorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='\u5c55\u793a\u6807\u9898')),
                ('title_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u5c55\u793a\u6807\u9898\uff08\u82f1\u6587\uff09')),
                ('order', models.IntegerField(default=0, verbose_name='\u987a\u5e8f\uff08\u53ea\u663e\u793a\u987a\u5e8f\u503c\u6700\u5927\u7684\u5185\u5bb9\uff09')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u8363\u8a89\u5c55\u793a\u89c6\u56fe',
                'verbose_name_plural': '\u8363\u8a89\u5c55\u793a\u89c6\u56fe',
            },
        ),
        migrations.CreateModel(
            name='Honors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='\u8363\u8a89\u540d\u79f0')),
                ('name_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u8363\u8a89\u540d\u79f0\uff08\u82f1\u6587\uff09')),
                ('order', models.IntegerField(default=0, verbose_name='\u987a\u5e8f\uff08\u53ea\u663e\u793a\u987a\u5e8f\u503c\u6700\u5927\u76848\u6761\u5185\u5bb9\uff09')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('own', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about_us.HonorInfo', verbose_name='\u6240\u5c5e')),
            ],
            options={
                'verbose_name': '\u8363\u8a89',
                'verbose_name_plural': '\u8363\u8a89',
            },
        ),
    ]
