# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-30 22:39
from __future__ import unicode_literals

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestMent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u59d3\u540d')),
                ('name_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u59d3\u540d\uff08\u82f1\u6587\uff09')),
                ('photo', models.ImageField(upload_to='investment/%Y/%m/%d', verbose_name='\u4e2a\u4eba\u7167\u7247\uff08375*375\uff09')),
                ('order', models.IntegerField(default=0, verbose_name='\u987a\u5e8f\uff08\u8d8a\u5927\u4f18\u5148\u7ea7\u8d8a\u9ad8\uff09')),
                ('description', models.TextField(verbose_name='\u4e2a\u4eba\u63cf\u8ff0')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='\u4e2a\u4eba\u63cf\u8ff0\uff08\u82f1\u6587\uff09')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u6295\u8d44\u56e2\u961f',
                'verbose_name_plural': '\u6295\u8d44\u56e2\u961f',
            },
        ),
        migrations.CreateModel(
            name='InvestPro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='\u6295\u8d44\u9879\u76ee\u540d\u79f0')),
                ('title_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u6295\u8d44\u9879\u76ee\u540d\u79f0\uff08\u82f1\u6587\uff09')),
                ('photo', models.ImageField(upload_to='investpro/%Y/%m/%d', verbose_name='\u9879\u76ee\u56fe\u7247\uff08450*450\uff09')),
                ('http_url', models.URLField(blank=True, null=True, verbose_name='\u9879\u76ee\u7f51\u5740')),
                ('description', models.TextField(verbose_name='\u9879\u76ee\u63cf\u8ff0')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='\u9879\u76ee\u63cf\u8ff0\uff08\u82f1\u6587\uff09')),
                ('order', models.IntegerField(default=0, verbose_name='\u987a\u5e8f\uff08\u8d8a\u5927\u4f18\u5148\u7ea7\u8d8a\u9ad8\uff09')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u6295\u8d44\u9879\u76ee',
                'verbose_name_plural': '\u6295\u8d44\u9879\u76ee',
            },
        ),
        migrations.CreateModel(
            name='InvestProCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='\u7c7b\u522b\u540d\u79f0')),
                ('name_en', models.CharField(blank=True, max_length=40, null=True, verbose_name='\u7c7b\u522b\u540d\u79f0\uff08\u82f1\u6587\uff09')),
                ('order', models.IntegerField(default=0, verbose_name='\u987a\u5e8f\uff08\u8d8a\u5927\u4f18\u5148\u7ea7\u8d8a\u9ad8\uff09')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u6295\u8d44\u9879\u76ee\u7c7b\u522b',
                'verbose_name_plural': '\u6295\u8d44\u9879\u76ee\u7c7b\u522b',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u6807\u9898')),
                ('title_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u6807\u9898\uff08\u82f1\u6587\uff09')),
                ('photo', models.ImageField(upload_to='news/%Y/%m/%d', verbose_name='\u65b0\u95fb\u5c01\u9762\uff08450*300\uff09')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='\u5185\u5bb9')),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='\u5185\u5bb9\uff08\u82f1\u6587\uff09')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u65b0\u95fb\u62a5\u9053',
            },
        ),
        migrations.AddField(
            model_name='investpro',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_manage.InvestProCategory', verbose_name='\u6295\u8d44\u9879\u76ee\u7c7b\u578b'),
        ),
    ]
