# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-30 22:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': '\u65b0\u95fb\u62a5\u9053', 'verbose_name_plural': '\u65b0\u95fb\u62a5\u9053'},
        ),
    ]
