# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-31 20:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_manage', '0002_auto_20170330_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u540d\u79f0\uff08\u6807\u8bc6\uff09')),
                ('address', models.CharField(max_length=100, verbose_name='\u5730\u5740')),
                ('address_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5730\u5740\uff08\u82f1\u6587\uff09')),
                ('phone', models.CharField(max_length=100, verbose_name='\u7535\u8bdd')),
                ('fax', models.CharField(max_length=100, verbose_name='\u4f20\u771f')),
                ('business_email', models.EmailField(max_length=254, verbose_name='\u5546\u4e1a\u8054\u7cfb\u90ae\u7bb1')),
                ('hr_email', models.EmailField(max_length=254, verbose_name='\u4eba\u4e8b\u62db\u8058\u90ae\u7bb1')),
                ('sina_qr', models.ImageField(blank=True, null=True, upload_to='contact/%Y/%m', verbose_name='\u65b0\u6d6a\u4e8c\u7ef4\u7801')),
                ('wechat_qr', models.ImageField(blank=True, null=True, upload_to='contact/%Y/%m', verbose_name='\u5fae\u4fe1\u4e8c\u7ef4\u7801')),
                ('map', models.ImageField(upload_to='contact/%Y/%m', verbose_name='\u516c\u53f8\u5730\u56fe')),
                ('order', models.IntegerField(default=0, verbose_name='\u987a\u5e8f\uff08\u53ea\u4f1a\u663e\u793a\u987a\u5e8f\u503c\u6700\u9ad8\u7684\u4e00\u7ec4\u4fe1\u606f\uff09')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u8054\u7cfb\u6211\u4eec',
                'verbose_name_plural': '\u8054\u7cfb\u6211\u4eec',
            },
        ),
    ]
